[versions]
twirl = "2.1.0-M5"
play = "3.1.0-M5-89408b5d-SNAPSHOT"
node = "7.1.0"
webjars-play = "3.1.0-M1"
flot = "0.8.3-1"
bootstrap = "3.4.1"
junit = "4.13.2"
assertj = "3.27.7"
awaitility = "4.3.0"

[libraries]
flot = { group = "org.webjars", name = "flot", version.ref = "flot" }
bootstrap = { group = "org.webjars", name = "bootstrap", version.ref = "bootstrap" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
awaitility = { group = "org.awaitility", name = "awaitility", version.ref = "awaitility" }

[plugins]
twirl = { id = "org.playframework.twirl", version.ref = "twirl" }
play = { id = "org.playframework.play", version.ref = "play" }
node = { id = "com.github.node-gradle.node", version.ref = "node" }
