[versions]
twirl = "2.1.0-M5"
play = "3.1.0-M4"
scalatestplus = "3.2.19.1"
scalatestplus-play = "8.0.0-M2"
log4j = "2.23.1"

[libraries]
log4j-slf4j-impl = { group = "org.apache.logging.log4j", name = "log4j-slf4j-impl", version.ref = "log4j" }
log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j" }
log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }
scalatest-junit5 = { group = "org.scalatestplus", name = "junit-5-10_2.13", version.ref = "scalatestplus" }
scalatestplus-play = { group = "org.scalatestplus.play", name = "scalatestplus-play_2.13", version.ref = "scalatestplus-play" }


[plugins]
twirl = { id = "org.playframework.twirl", version.ref = "twirl" }
play = { id = "org.playframework.play", version.ref = "play" }
