language: scala
scala:
# When updating Scala versions, also check the excludes
# in build matrix below.
- 2.11.12
- 2.12.6
jdk:
- oraclejdk8
- oraclejdk11
env:
  matrix:
    - SCRIPT=scripts/test-sbt
    - SCRIPT=scripts/test-gradle
script:
- $SCRIPT
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.gradle/caches"
before_cache:
- rm -rf $HOME/.ivy2/cache/com.typesafe.play/*
- rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print0 | xargs -n10 -0 rm

# Exclude some combinations from build matrix. See:
# https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix
matrix:
  fast_finish: true
  exclude:
    - scala: 2.11.12
      jdk: oraclejdk11
  allow_failures:
    # We should allow failures here since Java 11 removed some modules including
    # java.xml.bind which we are adding when running with Java 9+. For more details
    # see http://openjdk.java.net/jeps/320
    #
    # Play already has a fix for that, but it needs to be backported and released
    # for 2.6.x: https://github.com/playframework/playframework/pull/8382
    - jdk: oraclejdk11

# See https://blog.travis-ci.com/2014-03-13-slack-notifications/
# created with travis encrypt command line tool
notifications:
  slack:
    secure: PUp6/FRKg+EmERNdorpwfyrTbNkUaCPX1N7wUlUbS8z6ESIcm61Eqt63aQtlmVPg0THcpcjsX07nfCeKoAKzRAk31gcJ3XBBM2oHHM5/Bi4YzJgU/U+a2uFFnMlcoQqBmn5Ua2Kyaaqx43Hh+AO5aIKrsceglkau9UQOY9W4cwc=
