language: scala
scala: 2.13.0
script: eval "$SCRIPT"

env:
  global:
    - TRAVIS_JDK=8
  matrix:
    - SCRIPT="cd play-java-chatroom-example        && scripts/test-sbt"
    - SCRIPT="cd play-java-compile-di-example      && scripts/test-sbt"
    - SCRIPT="cd play-java-dagger2-example         && scripts/test-sbt"
    - SCRIPT="cd play-java-ebean-example           && scripts/test-sbt"
    - SCRIPT="cd play-java-fileupload-example      && scripts/test-sbt"
    - SCRIPT="cd play-java-forms-example           && scripts/test-sbt"
    - SCRIPT="cd play-java-grpc-example            && scripts/test-sbt"
    - SCRIPT="cd play-java-hello-world-tutorial    && scripts/test-sbt"
    - SCRIPT="cd play-java-jpa-example             && scripts/test-sbt"
    - SCRIPT="cd play-java-rest-api-example        && scripts/test-sbt"
    - SCRIPT="cd play-java-starter-example         && scripts/test-sbt"
    - SCRIPT="cd play-java-streaming-example       && scripts/test-sbt"
    - SCRIPT="cd play-java-websocket-example       && scripts/test-sbt"
    - SCRIPT="cd play-scala-anorm-example          && scripts/test-sbt"
    - SCRIPT="cd play-scala-chatroom-example       && scripts/test-sbt"
    - SCRIPT="cd play-scala-compile-di-example     && scripts/test-sbt"
    - SCRIPT="cd play-scala-fileupload-example     && scripts/test-sbt"
    - SCRIPT="cd play-scala-forms-example          && scripts/test-sbt"
    - SCRIPT="cd play-scala-grpc-example           && scripts/test-sbt"
    - SCRIPT="cd play-scala-hello-world-tutorial   && scripts/test-sbt"
    - SCRIPT="cd play-scala-isolated-slick-example && scripts/test-sbt"
    - SCRIPT="cd play-scala-log4j2-example         && scripts/test-sbt"
    - SCRIPT="cd play-scala-macwire-di-example     && scripts/test-sbt"
    - SCRIPT="cd play-scala-rest-api-example       && scripts/test-sbt"
    - SCRIPT="cd play-scala-secure-session-example && scripts/test-sbt"
    - SCRIPT="cd play-scala-slick-example          && scripts/test-sbt"
    - SCRIPT="cd play-scala-starter-example        && scripts/test-sbt"
    - SCRIPT="cd play-scala-streaming-example      && scripts/test-sbt"
    - SCRIPT="cd play-scala-tls-example            && scripts/test-sbt"
    - SCRIPT="cd play-scala-websocket-example      && scripts/test-sbt"

    - SCRIPT="cd play-java-chatroom-example        && scripts/test-sbt" TRAVIS_JDK=11
    - SCRIPT="cd play-java-compile-di-example      && scripts/test-sbt" TRAVIS_JDK=11
    - SCRIPT="cd play-java-dagger2-example         && scripts/test-sbt" TRAVIS_JDK=11
    - SCRIPT="cd play-java-ebean-example           && scripts/test-sbt" TRAVIS_JDK=11
    - SCRIPT="cd play-java-fileupload-example      && scripts/test-sbt" TRAVIS_JDK=11
    - SCRIPT="cd play-java-forms-example           && scripts/test-sbt" TRAVIS_JDK=11
    - SCRIPT="cd play-java-grpc-example            && scripts/test-sbt" TRAVIS_JDK=11
    - SCRIPT="cd play-java-hello-world-tutorial    && scripts/test-sbt" TRAVIS_JDK=11
    - SCRIPT="cd play-java-jpa-example             && scripts/test-sbt" TRAVIS_JDK=11
    - SCRIPT="cd play-java-rest-api-example        && scripts/test-sbt" TRAVIS_JDK=11
    - SCRIPT="cd play-java-starter-example         && scripts/test-sbt" TRAVIS_JDK=11
    - SCRIPT="cd play-java-streaming-example       && scripts/test-sbt" TRAVIS_JDK=11
    - SCRIPT="cd play-java-websocket-example       && scripts/test-sbt" TRAVIS_JDK=11
    - SCRIPT="cd play-scala-anorm-example          && scripts/test-sbt" TRAVIS_JDK=11
    - SCRIPT="cd play-scala-chatroom-example       && scripts/test-sbt" TRAVIS_JDK=11
    - SCRIPT="cd play-scala-compile-di-example     && scripts/test-sbt" TRAVIS_JDK=11
    - SCRIPT="cd play-scala-fileupload-example     && scripts/test-sbt" TRAVIS_JDK=11
    - SCRIPT="cd play-scala-forms-example          && scripts/test-sbt" TRAVIS_JDK=11
    - SCRIPT="cd play-scala-grpc-example           && scripts/test-sbt" TRAVIS_JDK=11
    - SCRIPT="cd play-scala-hello-world-tutorial   && scripts/test-sbt" TRAVIS_JDK=11
    - SCRIPT="cd play-scala-isolated-slick-example && scripts/test-sbt" TRAVIS_JDK=11
    - SCRIPT="cd play-scala-log4j2-example         && scripts/test-sbt" TRAVIS_JDK=11
    - SCRIPT="cd play-scala-macwire-di-example     && scripts/test-sbt" TRAVIS_JDK=11
    - SCRIPT="cd play-scala-rest-api-example       && scripts/test-sbt" TRAVIS_JDK=11
    - SCRIPT="cd play-scala-secure-session-example && scripts/test-sbt" TRAVIS_JDK=11
    - SCRIPT="cd play-scala-slick-example          && scripts/test-sbt" TRAVIS_JDK=11
    - SCRIPT="cd play-scala-starter-example        && scripts/test-sbt" TRAVIS_JDK=11
    - SCRIPT="cd play-scala-streaming-example      && scripts/test-sbt" TRAVIS_JDK=11
    - SCRIPT="cd play-scala-tls-example            && scripts/test-sbt" TRAVIS_JDK=11
    - SCRIPT="cd play-scala-websocket-example      && scripts/test-sbt" TRAVIS_JDK=11

matrix:
  fast_finish: true
  allow_failures:
    # Java 11 is not fully supported, look at and resolve these issues
    - env: SCRIPT="cd play-scala-tls-example            && scripts/test-sbt" TRAVIS_JDK=adopt@1.11.0-2

before_install:
  - sudo add-apt-repository -y ppa:ondrej/php && sudo apt-get -qq update && sudo apt-get install -y libsodium-dev # for secure session examples
  - curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install "adopt@~1.$TRAVIS_JDK.0-0" && jabba use "$_" && java -Xmx32m -version

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.jabba/jdk"
    - "$HOME/.sbt"

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt  -name "*.lock"               -delete
