[versions]
twirl = "2.0.6"
play = "3.0.1-03969c1e-SNAPSHOT"
ebean = "13.17.3" # Sync with Play Ebean version
play-ebean = "8.0.0-M1"
h2 = "2.2.224"
junit = "4.13.2"
assertj = "3.24.2"
awaitility = "4.2.1"
mockito = "5.12.0"

[libraries]
h2 = { group = "com.h2database", name = "h2", version.ref = "h2" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
awaitility = { group = "org.awaitility", name = "awaitility", version.ref = "awaitility" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
ebean-generator = { group = "io.ebean", name = "querybean-generator", version.ref = "ebean" }

[plugins]
ebean = { id = "io.ebean", version.ref = "ebean" }
twirl = { id = "org.playframework.twirl", version.ref = "twirl" }
play = { id = "org.playframework.play", version.ref = "play" }
