[versions]
twirl = "2.1.0-M5"
play = "3.1.0-M5-89408b5d-SNAPSHOT"
play-ebean = "9.0.0-M1"
ebean = "15.11.0" # Sync with Play Ebean version https://github.com/playframework/play-ebean/blob/main/project/Dependencies.scala#L19
h2 = "2.3.232"
junit = "4.13.2"
assertj = "3.27.7"
awaitility = "4.3.0"
mockito = "5.18.0"

[libraries]
h2 = { group = "com.h2database", name = "h2", version.ref = "h2" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
awaitility = { group = "org.awaitility", name = "awaitility", version.ref = "awaitility" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
play-ebean = { group ="org.playframework", name = "play-ebean_2.13", version.ref = "play-ebean" }

[plugins]
ebean = { id = "io.ebean", version.ref = "ebean" }
twirl = { id = "org.playframework.twirl", version.ref = "twirl" }
play = { id = "org.playframework.play", version.ref = "play" }
