[versions]
twirl = "2.1.0-M5"
play = "3.1.0-M5-89408b5d-SNAPSHOT"
scalatestplus = "3.2.19.1"
scalatestplus-play = "8.0.0-M2"
pekko = "1.2.1"

[libraries]
kalium = { group = "org.abstractj.kalium", name = "kalium", version = "0.8.0" }
jnr-ffi = { group = "com.github.jnr", name = "jnr-ffi", version = "2.2.18" }
pekko-distributed-data = { group = "org.apache.pekko", name = "pekko-distributed-data_2.13", version.ref = "pekko" }
scalatest-junit5 = { group = "org.scalatestplus", name = "junit-5-10_2.13", version.ref = "scalatestplus" }
scalatestplus-play = { group = "org.scalatestplus.play", name = "scalatestplus-play_2.13", version.ref = "scalatestplus-play" }


[plugins]
twirl = { id = "org.playframework.twirl", version.ref = "twirl" }
play = { id = "org.playframework.play", version.ref = "play" }
